name: Main Workflow

on:
    schedule:
        - cron: "15 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Feed the Snake
              uses: Platane/snk@v3
              with:
                github_user_name: svaleria
                outputs: |
                    img/github-snake.svg?palette=github-dark&color_snake=orange

            - name: Push Changes
              uses: crazy-max/ghaction-github-pages@v2.1.3
              with:
                target_branch: output
                build_dir: img
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}